### ISSUE TITLE
Which GPIO pin to use?

### ISSUE THREAD

**Issue by jaspersorrio** [electrovir/ws2812draw#1]
Hi there, cool library!

I can't seem to find which GPIO pin to use. Am i missing something here?

Thanks!

**Comment by jaspersorrio** [comment]
Hi all, dug deeper into the code base and realized that GPIO 18 (PIN 12) is the right pin to use.

**Comment by electrovir** [comment]
Hey! Glad you're liking it and found the pin. Unfortunately just last week it seems my Pi has died (I must've crossed the voltage pins or something and shorted it... or maybe my SD card has given up) so I hope this package works out for you cause I can't test it anymore at the current time 😢

**Comment by electrovir** [comment]
FYI added the [pin number to the README](https://github.com/electrovir/ws2812draw#hardware-setup)
